---
title: "쇼트트랙 데이터 분석"
author: "sht"
date: "2018년 2월 21일"
output: 

  html_document: 

    toc: true
    
    toc_float: true

    toc_depth: 2
---


# 1.데이터 읽기 및 확인
```{r}
short <- read.csv("C:\\Users\\HyunTaek\\Desktop\\study\\DoitR\\shorttrack\\shorttrack.csv", header = T)
head(short)
```


# 2.패키지 부착
```{r}
library(dplyr) 
library(ggplot2)
library(readr)
library(tidyr)
library(repr)
```

# 3.출발시간 분석

상위 10위 추출
```{r}
short %>%
  arrange(time_lap1) %>%
  head(10) %>%
  select(Season, Series, City, Round, Name, Nationality, time_lap1, Time)


short1 <- short %>%
  filter(time_lap1 < 8 & Nationality %in%
           c("CAN", "KOR", "RUS", "HUN", "USA", "GBR", "KAZ", "NED", "ITA")) %>%
  drop_na()

options(repr.plot.width = 5.5, repr.plot.height = 4)

ggplot(short1, aes(Nationality, time_lap1))+
  geom_boxplot()+
  labs(title = "Distribution of Starting Time By Skaters Nationality")
```


# 4.데이터 형태 확인
```{r}
table(short$Distance)
table(short$Nationality)
```



# 5.국가별 총 시간 분류
```{r}
nation <- short %>%
  filter(!is.na(Time)) %>%
  group_by(Nationality) %>%
  summarise(time = mean(Time))
head(nation)
```



# 6.총 시간 기록 상위 10개국
```{r}
top10 <- nation %>% 
  arrange(time) %>% 
  head(10)
top10
```



## 6-1.막대 그래프 만들기
```{r}
ggplot(data = top10, aes(x=Nationality, y= time)) + 
  geom_col()+
  coord_flip(ylim = c(42,44))+
  scale_x_discrete(limits=rev(top10$Nationality)) # 역순 출력은 rev
```



# 7.총 시간 기록 하위 10개국
```{r}
bottom10 <- nation %>%
  arrange(desc(time)) %>%
  head(10)
bottom10
```



## 7-1.막대 그래프 만들기
```{r}
ggplot(data = bottom10, aes(x=Nationality, y= time))+
  geom_col()+
  coord_flip(ylim=c(47,53))+
  scale_x_discrete(limits=rev(bottom10$Nationality)) # 역순 출력은 rev
```