install.packages("ggmap")
library(ggmap)

map<- get_map(location = "Dong-gu, Daejeon", zoom=13, maptype="roadmap", source="google")
map2<-get_map(location = "Yuseong-gu, Daejeon", zoom=13, maptype="roadmap", source="google")
g<-ggmap(map)
g2<-ggmap(map2)
print(g)
print(g2)
landmarks<-c("Expo Plaza, Daejeon", "Jangtaesan Mountain Natural Recreation Forest, Daejeon")
landmarks2<-c("Chungnam National Univ. Library, Daejeon","Korea Advanced Institute of Science and Technology, Yuseong-gu, Daejeon")
lbls<- cbind(geocode(landmarks), text=landmarks)
lbls2<- cbind(geocode(landmarks2), text=landmarks2)
g<-ggmap(map)
g<-g+geom_point(data=lbls, aes(x=lon, y=lat), size=5, colour="orange")
g<-g+geom_point(data=lbls, aes(x=lon, y=lat), size=3, colour="red")
g<-g+geom_text(data=lbls, aes(x=lon, y=lat, label=text), size=5, colour="blue", hjust=0, vjust=0)
print(g)
